package org.reprogle.honeypot.util;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.Material;

public class PhysicsBlocks {

	private List<Material> physicsUp = new ArrayList<>();
	private List<Material> physicsSide = new ArrayList<>();

	// I gave up on alphabetizing this list lol
	public PhysicsBlocks() {
		physicsUp.add(Material.ACACIA_DOOR);
        physicsUp.add(Material.ACACIA_PRESSURE_PLATE);
        physicsUp.add(Material.ACACIA_SAPLING);
        physicsUp.add(Material.ACACIA_SIGN);
        physicsUp.add(Material.ACTIVATOR_RAIL);
        physicsUp.add(Material.ALLIUM);
		physicsUp.add(Material.AMETHYST_CLUSTER);
        physicsUp.add(Material.ATTACHED_MELON_STEM);
        physicsUp.add(Material.ATTACHED_PUMPKIN_STEM);
        physicsUp.add(Material.AZURE_BLUET);
		physicsUp.add(Material.AZALEA);
        physicsUp.add(Material.BAMBOO_SAPLING);
        physicsUp.add(Material.BEETROOTS);
        physicsUp.add(Material.BELL);
		physicsUp.add(Material.BIG_DRIPLEAF);
		physicsUp.add(Material.BIG_DRIPLEAF_STEM);
        physicsUp.add(Material.BIRCH_DOOR);
        physicsUp.add(Material.BIRCH_PRESSURE_PLATE);
        physicsUp.add(Material.BIRCH_SAPLING);
        physicsUp.add(Material.BIRCH_SIGN);
        physicsUp.add(Material.BLACK_BANNER);
		physicsUp.add(Material.BLACK_CANDLE);
		physicsUp.add(Material.BLACK_CANDLE_CAKE);
        physicsUp.add(Material.BLACK_CARPET);
        physicsUp.add(Material.BLUE_BANNER);
        physicsUp.add(Material.BLUE_CARPET);
		physicsUp.add(Material.BLUE_CANDLE);
		physicsUp.add(Material.BLUE_CANDLE_CAKE);
        physicsUp.add(Material.BLUE_ORCHID);
        physicsUp.add(Material.BROWN_BANNER);
        physicsUp.add(Material.BROWN_CARPET);
		physicsUp.add(Material.BROWN_CANDLE);
		physicsUp.add(Material.BROWN_CANDLE_CAKE);
        physicsUp.add(Material.BROWN_MUSHROOM);
		physicsUp.add(Material.BUDDING_AMETHYST);
		physicsUp.add(Material.CANDLE);
        physicsUp.add(Material.CAKE);
        physicsUp.add(Material.CARROTS);
        physicsUp.add(Material.COMPARATOR);
        physicsUp.add(Material.CORNFLOWER);
        physicsUp.add(Material.CYAN_BANNER);
		physicsUp.add(Material.CYAN_CANDLE);
		physicsUp.add(Material.CYAN_CANDLE_CAKE);
        physicsUp.add(Material.CYAN_CARPET);
        physicsUp.add(Material.DANDELION);
        physicsUp.add(Material.DARK_OAK_DOOR);
        physicsUp.add(Material.DARK_OAK_PRESSURE_PLATE);
        physicsUp.add(Material.DARK_OAK_SAPLING);
        physicsUp.add(Material.DARK_OAK_SIGN);
        physicsUp.add(Material.DEAD_BUSH);
        physicsUp.add(Material.DETECTOR_RAIL);
        physicsUp.add(Material.FERN);
        physicsUp.add(Material.FIRE);
		physicsUp.add(Material.FLOWERING_AZALEA);
		physicsUp.add(Material.FROGSPAWN);
		physicsUp.add(Material.FROG_SPAWN_EGG);
		physicsUp.add(Material.GLOW_LICHEN);
        physicsUp.add(Material.GRASS);
        physicsUp.add(Material.GRAY_BANNER);
		physicsUp.add(Material.GRAY_CANDLE);
		physicsUp.add(Material.GRAY_CANDLE_CAKE);
        physicsUp.add(Material.GRAY_CARPET);
        physicsUp.add(Material.GREEN_BANNER);
		physicsUp.add(Material.GREEN_CANDLE);
		physicsUp.add(Material.GREEN_CANDLE_CAKE);
        physicsUp.add(Material.GREEN_CARPET);
		physicsUp.add(Material.HANGING_ROOTS);
        physicsUp.add(Material.HEAVY_WEIGHTED_PRESSURE_PLATE);
        physicsUp.add(Material.IRON_DOOR);
        physicsUp.add(Material.JUNGLE_DOOR);
        physicsUp.add(Material.JUNGLE_PRESSURE_PLATE);
        physicsUp.add(Material.JUNGLE_SAPLING);
        physicsUp.add(Material.JUNGLE_SIGN);
        physicsUp.add(Material.LANTERN);
        physicsUp.add(Material.LARGE_FERN);
        physicsUp.add(Material.LIGHT_BLUE_BANNER);
		physicsUp.add(Material.LIGHT_BLUE_CANDLE);
		physicsUp.add(Material.LIGHT_BLUE_CANDLE_CAKE);
        physicsUp.add(Material.LIGHT_BLUE_CARPET);
        physicsUp.add(Material.LIGHT_GRAY_BANNER);
		physicsUp.add(Material.LIGHT_GRAY_CANDLE);
		physicsUp.add(Material.LIGHT_GRAY_CANDLE_CAKE);
        physicsUp.add(Material.LIGHT_GRAY_CARPET);
        physicsUp.add(Material.LIGHT_WEIGHTED_PRESSURE_PLATE);
        physicsUp.add(Material.LILAC);
        physicsUp.add(Material.LILY_OF_THE_VALLEY);
        physicsUp.add(Material.LILY_PAD);
        physicsUp.add(Material.LIME_BANNER);
		physicsUp.add(Material.LIME_CANDLE);
		physicsUp.add(Material.LIME_CANDLE_CAKE);
        physicsUp.add(Material.LIME_CARPET);
        physicsUp.add(Material.MAGENTA_BANNER);
		physicsUp.add(Material.MAGENTA_CANDLE);
		physicsUp.add(Material.MAGENTA_CANDLE_CAKE);
        physicsUp.add(Material.MAGENTA_CARPET);
		physicsUp.add(Material.MANGROVE_PROPAGULE);
        physicsUp.add(Material.MELON_STEM);
		physicsUp.add(Material.MOSS_CARPET);
        physicsUp.add(Material.NETHER_PORTAL);
        physicsUp.add(Material.NETHER_WART);
        physicsUp.add(Material.OAK_DOOR);
        physicsUp.add(Material.OAK_PRESSURE_PLATE);
        physicsUp.add(Material.OAK_SAPLING);
        physicsUp.add(Material.OAK_SIGN);
        physicsUp.add(Material.ORANGE_BANNER);
		physicsUp.add(Material.ORANGE_CANDLE);
		physicsUp.add(Material.ORANGE_CANDLE_CAKE);
        physicsUp.add(Material.ORANGE_CARPET);
        physicsUp.add(Material.ORANGE_TULIP);
        physicsUp.add(Material.OXEYE_DAISY);
        physicsUp.add(Material.PEONY);
        physicsUp.add(Material.PINK_BANNER);
		physicsUp.add(Material.PINK_CANDLE);
		physicsUp.add(Material.PINK_CANDLE_CAKE);
        physicsUp.add(Material.PINK_CARPET);
        physicsUp.add(Material.PINK_TULIP);
		physicsUp.add(Material.POINTED_DRIPSTONE);
        physicsUp.add(Material.POPPY);
        physicsUp.add(Material.POTATOES);
        physicsUp.add(Material.POWERED_RAIL);
        physicsUp.add(Material.PUMPKIN_STEM);
        physicsUp.add(Material.PURPLE_BANNER);
		physicsUp.add(Material.PURPLE_CANDLE);
		physicsUp.add(Material.PURPLE_CANDLE_CAKE);
        physicsUp.add(Material.PURPLE_CARPET);
        physicsUp.add(Material.RAIL);
        physicsUp.add(Material.REDSTONE_TORCH);
        physicsUp.add(Material.REDSTONE_WIRE);
        physicsUp.add(Material.RED_BANNER);
		physicsUp.add(Material.RED_CANDLE);
		physicsUp.add(Material.RED_CANDLE_CAKE);
        physicsUp.add(Material.RED_CARPET);
        physicsUp.add(Material.RED_MUSHROOM);
        physicsUp.add(Material.RED_TULIP);
        physicsUp.add(Material.REPEATER);
        physicsUp.add(Material.ROSE_BUSH);
		physicsUp.add(Material.SCULK_VEIN);
        physicsUp.add(Material.SNOW);
		physicsUp.add(Material.SMALL_DRIPLEAF);
        physicsUp.add(Material.SPRUCE_DOOR);
        physicsUp.add(Material.SPRUCE_PRESSURE_PLATE);
        physicsUp.add(Material.SPRUCE_SAPLING);
        physicsUp.add(Material.SPRUCE_SIGN);
        physicsUp.add(Material.STONE_PRESSURE_PLATE);
        physicsUp.add(Material.SUNFLOWER);
        physicsUp.add(Material.SWEET_BERRY_BUSH);
        physicsUp.add(Material.TALL_GRASS);
        physicsUp.add(Material.TORCH);
        physicsUp.add(Material.SAND);
        physicsUp.add(Material.RED_SAND);
        physicsUp.add(Material.ANVIL);
        physicsUp.add(Material.GRAVEL);
        physicsUp.add(Material.WHEAT);
        physicsUp.add(Material.WHITE_BANNER);
		physicsUp.add(Material.WHITE_CANDLE);
		physicsUp.add(Material.WHITE_CANDLE_CAKE);
        physicsUp.add(Material.WHITE_CARPET);
        physicsUp.add(Material.WHITE_TULIP);
        physicsUp.add(Material.WITHER_ROSE);
        physicsUp.add(Material.YELLOW_BANNER);
		physicsUp.add(Material.YELLOW_CANDLE);
		physicsUp.add(Material.YELLOW_CANDLE_CAKE);
        physicsUp.add(Material.YELLOW_CARPET);
		physicsUp.add(Material.CRIMSON_FUNGUS);
		physicsUp.add(Material.WARPED_FUNGUS);
		physicsUp.add(Material.CRIMSON_ROOTS);
		physicsUp.add(Material.WARPED_ROOTS);
		physicsUp.add(Material.SOUL_FIRE);
		physicsUp.add(Material.SOUL_TORCH);
		physicsUp.add(Material.TWISTING_VINES);
		physicsUp.add(Material.TWISTING_VINES_PLANT);
		physicsUp.add(Material.WEEPING_VINES);
		physicsUp.add(Material.WEEPING_VINES_PLANT);
       
		physicsSide.add(Material.AMETHYST_CLUSTER);
		physicsSide.add(Material.BUDDING_AMETHYST);
        physicsSide.add(Material.LADDER);
        physicsSide.add(Material.OAK_BUTTON);
        physicsSide.add(Material.SPRUCE_BUTTON);
        physicsSide.add(Material.ACACIA_BUTTON);
        physicsSide.add(Material.BIRCH_BUTTON);
        physicsSide.add(Material.JUNGLE_BUTTON);
        physicsSide.add(Material.DARK_OAK_BUTTON);
        physicsSide.add(Material.OAK_SIGN);
        physicsSide.add(Material.SPRUCE_SIGN);
        physicsSide.add(Material.ACACIA_SIGN);
        physicsSide.add(Material.BIRCH_SIGN);
        physicsSide.add(Material.JUNGLE_SIGN);
        physicsSide.add(Material.DARK_OAK_SIGN);
        physicsSide.add(Material.SPRUCE_TRAPDOOR);
        physicsSide.add(Material.ACACIA_TRAPDOOR);
        physicsSide.add(Material.BIRCH_TRAPDOOR);
        physicsSide.add(Material.JUNGLE_TRAPDOOR);
        physicsSide.add(Material.DARK_OAK_TRAPDOOR);
        physicsSide.add(Material.STONE_BUTTON);
        physicsSide.add(Material.TORCH);
        physicsSide.add(Material.REDSTONE_TORCH);
        physicsSide.add(Material.LEVER);
        physicsSide.add(Material.TRIPWIRE);
		physicsSide.add(Material.CAVE_VINES);
		physicsSide.add(Material.CAVE_VINES_PLANT);
		physicsSide.add(Material.GLOW_LICHEN);
		physicsSide.add(Material.SOUL_TORCH);
	}

	public List<Material> getPhysicsUp() {
		return physicsUp;
	}

	public List<Material> getPhysicsSide() {
		return physicsSide;
	}
	
}
