name: Honeypot
version: '${project.version}'
author: TerrorByte
description: Creates honeypot blocks designed to prevent griefing on your server
main: org.reprogle.honeypot.Honeypot
api-version: 1.17
load: STARTUP
folia-supported: true
softdepend: [ Vault, WorldGuard, GriefPrevention, Lands, PlaceholderAPI ]
commands:
  honeypot:
    description: Creates or deletes a honeypot block
    aliases: [ hp ]

permissions:
  honeypot.gui:
    description: Allows a user to use the Honeypot GUI
    default: op
  honeypot.commands:
    description: Allows a user to use Honeypot commands (necessary for all commands)
    default: op
  honeypot.create:
    description: Allows a user to create Honeypot blocks
    default: op
  honeypot.break:
    description: Allows a user to remove Honeypot blocks
    default: op
  honeypot.remove:
    description: Allows players to remove Honeypots with the command, but not break them
    default: op
  honeypot.locate:
    description: Allows a user to see nearby Honeypot blocks
    default: op
  honeypot.exempt:
    description: Exempts a player from break actions
    default: op
  honeypot.notify:
    description: Allows user to be notified of Honeypot breaks
    default: op
  honeypot.reload:
    description: Allows user to reload the config
    default: op
  honeypot.update:
    description: Notifies player on join if a Honeypot plugin update is available
    default: op
  honeypot.history:
    description: Allows querying and modifying the history table
    default: op
  honeypot.teleport:
    description: Allows for staff to teleport to Honeypot blocks within the GUI
    default: op
  honeypot.*:
    description: Allows all Honeypot permissions
    default: op
    children:
      honeypot.commands: true
      honeypot.create: true
      honeypot.break: true
      honeypot.remove: true
      honeypot.exempt: true
      honeypot.notify: true
      honeypot.reload: true
      honeypot.locate: true
      honeypot.update: true
      honeypot.history: true
      honeypot.teleport: true
